export const dedicatedCopy = {
  zh: {
    staleError: '包号已被其他操作修改。请取消编辑、刷新列表后重新打开，不要直接重试旧表单。', restoreError: '请勾选确认恢复已撤销包号后再保存。', restoreConfirm: '我确认恢复此包号，允许所选成员重新使用',
    configHealth: { valid: '配置检查通过（不代表上游实时可用）', invalid_structure: '配置异常：检查账号独占、分组状态、平台、备用路由及非成员授权', member_warning: '成员或密钥待处理：检查成员状态、组授权及非成员密钥；正常成员不受其他成员停用影响', unknown: '配置状态未读取，请刷新' } as Record<string, string>,
    title: '我的专属账号', adminTitle: '包号管理', description: '查看专属账号的可用状态与上游配额快照。', adminDescription: '将独立账号绑定给指定用户，并管理包号有效期。',
    refresh: '刷新状态', loading: '正在读取…', loadError: '读取失败，请重试。', empty: '还没有专属账号', emptyHint: '管理员完成包号分配后，账号会显示在这里。', adminEmpty: '还没有包号记录',
    quotaHint: '剩余比例来自上游最近一次采样，不是本站余额。刷新只读取快照，不发送模型请求；超过15分钟或窗口已重置时不显示旧比例。',
    statusHint: '状态来自本站账号记录，不代表上游实时在线或所有模型均可调用。不可用时不会自动切换到共享账号。',
    expires: '包号到期', lastUsed: '最近使用', sampled: '额度采样', checked: '状态读取', unknown: '暂不可获取', never: '暂无记录', remaining: '剩余', resets: '重置时间', noQuota: '暂无有效额度快照。正常请求产生上游额度信息后，再刷新查看。',
    group: '专属分组', keyHint: '选择获准的专属分组密钥使用有效包号，实扣0，余额为0也可使用。普通分组仍正常计费；请求限制沿用平台通用配置。', keys: '管理密钥', contact: '如需续期或账号暂不可用，请联系管理员。',
    previous: '上一页', next: '下一页', page: '页', create: '新增包号', edit: '修改 / 续期', cancel: '取消', save: '保存绑定', saving: '正在保存…', saved: '绑定已保存。', revoked: '包号已撤销；账号继续隔离，不会自动放回共享池。',
    revoke: '撤销包号', revokeQuestion: '确认撤销这个包号？后续请求会被拒绝，已在处理的请求可能继续完成。', confirmRevoke: '确认撤销',
    setupTitle: '先准备专属分组', setup: '账号可加入同一批包号成员使用的多个同平台标准专属分组，各组仅放此账号且不设置备用路由。先给全部成员授权本次绑定分组；其他关联组可按需授权这些成员。公开分组仍可正常使用，但此包号账号不能加入公开池。关联组存在名单外授权或未停用密钥、订阅或影子账号时不能绑定。',
    setupLinks: '配置入口', groups: '分组管理', users: '用户管理', accounts: '账号管理',
    billing: '有效包号在获准的专属组内使用实扣0，不要求账户余额；普通组仍正常计费。包号仅管理账号归属、有效期与免扣；并发、请求频率和生图权限沿用平台通用配置。',
    platform: '平台', user: '指定用户', account: '上游账号', label: '用户可见别名', labelHint: '例如：我的 Claude 专属账号。不要填写邮箱、Token 或内部备注。', until: '到期时间（本机时区）',
    search: '搜索', searchPlaceholder: '输入名称、邮箱或关键词', choose: '请选择', noChoices: '未找到匹配项，请调整搜索或检查配置。', searchHint: '每次显示前30项，请用关键词缩小范围。',
    editHint: '可更换账号、分组及成员；新增成员需先准备绑定分组授权。保存时会撤销移除成员在原账号关联专属组的授权，并停用这些组内的密钥（保留记录，不影响无关分组）。旧密钥不会自动迁移分组。已撤销记录需要明确确认才能恢复。',
    membersHint: '可指定多位不同用户，各自使用自己的API Key，共享上游账号额度。普通分组消费仍从各自余额扣除。同一账号只创建一条包号；它关联的多个专属组仅授权这批成员。', addUser: '添加用户', removeUser: '移除用户',
    delete: '删除记录', confirmDelete: '确认删除', deleted: '记录已删除，旧密钥隔离仍保留。', deleteQuestion: '删除这条已撤销记录？它将从列表移除，不删除用户、上游账号或分组；旧密钥仍受隔离保护。',
    validInput: '请完整选择用户、账号、分组，填写别名并选择未来的到期时间。',
    modeError: '包号功能仅支持标准运行模式。', configError: '配置不满足独占条件。请按准备说明检查分组、授权、密钥、订阅及影子账号。', conflict: '账号或分组已有包号记录，请修改原记录。', saveError: '操作失败，请检查配置后重试。',
    active: '生效中', expired: '已到期', revokedStatus: '已撤销', id: '记录',
    statuses: { available: '正常', rate_limited: '限流中', unavailable: '暂不可用', configuration_error: '分配配置异常', expired: '已到期', revoked: '已撤销' } as Record<string, string>,
    windows: { five_hour: '5小时额度', seven_day: '7天额度', seven_day_sonnet: 'Sonnet 7天额度', seven_day_fable: 'Fable 7天额度' } as Record<string, string>
  },
  en: {
    staleError: 'This assignment changed. Cancel editing, refresh the list and reopen it before saving.', restoreError: 'Confirm restoration of this revoked assignment before saving.', restoreConfirm: 'Restore this assignment and allow the selected members to use it again',
    configHealth: { valid: 'Configuration checked (not a live upstream availability check)', invalid_structure: 'Invalid configuration: check account isolation, group status, platform, fallback routes and non-member access', member_warning: 'Review member status, group access and non-member keys; disabled peers do not block healthy members', unknown: 'Configuration not checked. Refresh the list.' } as Record<string, string>,
    title: 'My dedicated accounts', adminTitle: 'Dedicated accounts', description: 'Account availability and upstream quota snapshots.', adminDescription: 'Assign isolated accounts to users and manage access expiry.',
    refresh: 'Refresh status', loading: 'Loading…', loadError: 'Could not load. Please retry.', empty: 'No dedicated accounts yet', emptyHint: 'Accounts appear here after an administrator assigns them.', adminEmpty: 'No assignments yet',
    quotaHint: 'Remaining percentages come from upstream snapshots, not your site balance. Refresh does not send model requests. Snapshots older than 15 minutes or past their reset time are not shown as current.',
    statusHint: 'Status reflects local account records, not live upstream health or availability of every model. Unavailable accounts do not fall back to the shared pool.',
    expires: 'Access expires', lastUsed: 'Last used', sampled: 'Quota sampled', checked: 'Status read', unknown: 'Unavailable', never: 'No record', remaining: 'Remaining', resets: 'Resets at', noQuota: 'No current quota snapshot. Refresh after a normal request provides upstream quota information.',
    group: 'Dedicated group', keyHint: 'Use an authorized dedicated-group key for zero-billed access, even with zero balance. Public groups retain normal billing. Standard platform request limits apply.', keys: 'Manage API keys', contact: 'Contact the administrator for renewal or account issues.',
    previous: 'Previous', next: 'Next', page: 'Page', create: 'New assignment', edit: 'Edit / renew', cancel: 'Cancel', save: 'Save assignment', saving: 'Saving…', saved: 'Assignment saved.', revoked: 'Assignment revoked. The account stays isolated and is not returned to the shared pool.',
    revoke: 'Revoke', revokeQuestion: 'Revoke this assignment? New requests will be denied. Requests already in progress may finish.', confirmRevoke: 'Confirm revoke',
    setupTitle: 'Prepare exclusive groups first', setup: 'An account may join multiple same-platform standard exclusive groups for the same assignment members. Each group contains only this account and has no fallback routes. Authorize every member in the primary group, and authorize these members in other linked groups as needed. Members may still use public groups, but this account cannot join the public pool. Outside users’ access or enabled keys, subscriptions, and shadow accounts prevent assignment.',
    setupLinks: 'Configure', groups: 'Groups', users: 'Users', accounts: 'Accounts', billing: 'Valid dedicated usage is billed at zero without a balance requirement. Public groups retain normal billing. Assignments manage account ownership, expiry and zero billing only. Concurrency, request rates and image permissions follow standard platform settings.',
    platform: 'Platform', user: 'Assigned user', account: 'Upstream account', label: 'User-facing label', labelHint: 'For example: My dedicated Claude account. Do not include email, tokens, or internal notes.', until: 'Expires at (local timezone)',
    search: 'Search', searchPlaceholder: 'Name, email, or keyword', choose: 'Select an option', noChoices: 'No matches. Adjust your search or check configuration.', searchHint: 'Showing up to 30 results. Use a keyword to narrow the list.',
    editHint: 'Account, group and members can change. Prepare primary-group access for new members first. Saving revokes departing members’ access and disables their keys in the previous account’s linked exclusive groups, preserving records and unrelated groups. Keys are not moved to the new group. Restoring a revoked assignment requires explicit confirmation.',
    membersHint: 'Select distinct users with their own API keys, sharing upstream account quota. Public-group usage still charges each user’s balance. Create one assignment per account; its linked exclusive groups may authorize only these members.', addUser: 'Add user', removeUser: 'Remove user',
    delete: 'Delete record', confirmDelete: 'Confirm deletion', deleted: 'Record deleted. Old keys remain isolated.', deleteQuestion: 'Delete this revoked record from the list? Users, accounts and groups are not deleted. Old keys remain isolated.',
    validInput: 'Select a user, account, group, label, and a future expiry.', modeError: 'Dedicated accounts require standard runtime mode.', configError: 'Isolation checks failed. Review the group, access, keys, subscriptions, and shadow accounts.', conflict: 'This account or group already has an assignment. Edit the existing record.', saveError: 'Operation failed. Check configuration and retry.',
    active: 'Active', expired: 'Expired', revokedStatus: 'Revoked', id: 'Assignment',
    statuses: { available: 'Active', rate_limited: 'Rate limited', unavailable: 'Unavailable', configuration_error: 'Assignment configuration error', expired: 'Expired', revoked: 'Revoked' } as Record<string, string>,
    windows: { five_hour: '5-hour quota', seven_day: '7-day quota', seven_day_sonnet: 'Sonnet 7-day quota', seven_day_fable: 'Fable 7-day quota' } as Record<string, string>
  }
}
