export const intelligenceCopy = {
  zh: {
    title: '智力效率', description: '看能力，也看完成任务的代价。', refresh: '刷新数据', refreshing: '正在同步',
    updated: '评测数据更新', fetched: '本页获取',
    intro: '让模型选择，有据可依。', summary: '同一来源的评测分数、推理档位与任务效率，在这里一起比较。',
    models: '覆盖模型', points: '评测组合', samples: '低样本组合', matrix: '智力矩阵', chart: '效率对比',
    search: '搜索模型名称', harness: '评测环境', all: '全部环境', robust: '仅看 ≥30 个有效样本',
    matrixHint: '模型 × 推理档位；不同评测环境独立展示。', model: '模型 / 环境', score: '源站 IQ 分数',
    missing: '暂无数据', passed: '通过 / 有效样本', low: '低样本', unknown: '样本未知',
    chartHint: '每行一个模型与档位，直接对比得分、耗时和费用；不同环境不合并，不计算综合排名。',
    time: '任务耗时（分钟）', cost: '任务参考费用（美元）', empty: '没有符合条件的数据', reset: '清除筛选',
    loading: '正在读取 Codex Radar 评测数据…', error: '数据源暂时不可用或格式发生变化，请稍后重试。',
    retained: '刷新失败，仍显示上次成功获取的数据。', stale: '源数据距今已超过 24 小时，不代表实时评测。',
    note: 'IQ 是源站评测指标，不是人类智商；不同环境、样本数和推理档位会影响可比性。',
    sampleNote: '少于 30 个有效样本标记为低样本；30 只是展示筛选阈值，不是统计可信度保证。缺失数据不按 0 分处理。',
    sort: '矩阵排序', sourceOrder: '数据源原始顺序', nameOrder: '模型名称 A–Z', scoreOrder: '分数从高到低',
    orderHint: '默认按数据源中模型首次出现的顺序，不是智力排名。按档位排序时缺失分数排最后，同分保留原顺序。',
    compareEffort: '对比档位', allEfforts: '全部档位', compareSort: '对比排序', iqOrder: '得分从高到低', timeOrder: '耗时从少到多', costOrder: '费用从低到高',
    higher: '越高越好', lower: '越低越好', scaleNote: '条长按当前筛选结果各指标最大值缩放；三个指标单位不同，不能跨列比较条长。',
    shown: '显示组合', previous: '上一页', next: '下一页',
    details: '查看图表数据明细', effort: '推理档位', aggregation: '费用聚合', noMetric: '无可绘制的分数或效率数据',
    ultra: '极致', max: '最高', xhigh: '超高', high: '高', medium: '中', lowEffort: '低'
  },
  en: {
    title: 'Intelligence & efficiency', description: 'Compare capability and the cost of completing a task.', refresh: 'Refresh data', refreshing: 'Syncing',
    updated: 'Source updated', fetched: 'Fetched here',
    intro: 'Choose models with evidence.', summary: 'Compare benchmark scores, reasoning effort and task efficiency from a single source.',
    models: 'Models covered', points: 'Test configurations', samples: 'Small samples', matrix: 'Intelligence matrix', chart: 'Efficiency comparison',
    search: 'Search model names', harness: 'Evaluation harness', all: 'All harnesses', robust: 'Only ≥30 valid samples',
    matrixHint: 'Models × reasoning effort; harnesses are kept separate.', model: 'Model / harness', score: 'Source IQ score',
    missing: 'No data', passed: 'Passed / valid samples', low: 'Small sample', unknown: 'Unknown sample',
    chartHint: 'One model and effort per row. Compare scores, duration and cost directly. Harnesses stay separate; no combined ranking is calculated.',
    time: 'Task duration (minutes)', cost: 'Reference task cost (USD)', empty: 'No matching data', reset: 'Clear filters',
    loading: 'Loading Codex Radar benchmark data…', error: 'The source is unavailable or its format has changed. Please retry.',
    retained: 'Refresh failed. Showing the last successful snapshot.', stale: 'Source data is over 24 hours old, not a real-time evaluation.',
    note: 'IQ is a source benchmark metric, not human IQ. Harness, sample size and effort affect comparability.',
    sampleNote: 'Fewer than 30 valid samples are marked as small samples. The threshold is a display filter, not a statistical confidence guarantee. Missing data is not treated as zero.',
    sort: 'Matrix order', sourceOrder: 'Original source order', nameOrder: 'Model name A–Z', scoreOrder: 'Score, high to low',
    orderHint: 'Default order follows each model’s first appearance in the source, not intelligence rank. Missing scores sort last; ties keep source order.',
    compareEffort: 'Compare effort', allEfforts: 'All efforts', compareSort: 'Comparison order', iqOrder: 'Score, high to low', timeOrder: 'Duration, low to high', costOrder: 'Cost, low to high',
    higher: 'Higher is better', lower: 'Lower is better', scaleNote: 'Bars use each metric’s maximum across the current filter. Units differ, so do not compare bar lengths across columns.',
    shown: 'Configurations shown', previous: 'Previous', next: 'Next',
    details: 'View plot data', effort: 'Reasoning effort', aggregation: 'Cost aggregation', noMetric: 'No score or efficiency data to plot',
    ultra: 'Ultra', max: 'Max', xhigh: 'Extra high', high: 'High', medium: 'Medium', lowEffort: 'Low'
  }
}
