import { items, plays, typeLabels } from './catalog.mjs';
import { icon } from './icons.mjs';
import { STORE_KEY, makeStore, findItems, compile, exportText, itemFromHash } from './core.mjs';

const $ = id => document.getElementById(id);
const el = (tag, cls, text) => { const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; };
const decorate = (n,name,text) => { n.replaceChildren(icon(name));if(text)n.append(document.createTextNode(text));return n; };
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('storage');},setItem(){throw Error('storage');}};}
const store=makeStore(storage,items.map(x=>x.id));
const state={section:'discover',media:'all',type:'all',category:'all',query:'',sort:'featured'};
const drafts=new Map();let selected=itemFromHash(location.hash,items)||items[0],language='zh',toastTimer,motionPlaying=false;
const headings={discover:['灵感，从这里开始。','找一个喜欢的效果，做成自己的作品。'],skills:['把方法，接进工作流。','从官方技能和模板开始，先准备好环境。'],plays:['好玩的，不止一个提示词。','把画面、镜头和工具串成一次创作。'],saved:['留给下一次的灵感。','收藏保存在当前浏览器，随时回来继续。'],history:['刚刚看过的灵感。','最近浏览只记录条目，不记录你的材料。']};
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>{$('toast').hidden=true;},4200);}
function persist(next){const ok=store.write(next);if(!ok)toast('浏览器存储不可用，本次收藏与浏览记录只在当前页保留。');return ok;}
function applyTheme(){document.documentElement.dataset.theme=store.data.theme;decorate($('theme-toggle'),store.data.theme==='dark'?'sun':'moon');$('theme-toggle').setAttribute('aria-label',store.data.theme==='dark'?'切换到浅色主题':'切换到深色主题');}
function saveButton(button,item){const saved=store.data.favorites.includes(item.id);decorate(button,'bookmark');button.classList.toggle('saved',saved);button.setAttribute('aria-label',`${saved?'取消收藏':'收藏'}：${item.title}`);button.setAttribute('aria-pressed',String(saved));button.dataset.saveId=item.id;}
function toggleFavorite(item){const favorites=store.data.favorites.includes(item.id)?store.data.favorites.filter(x=>x!==item.id):[...store.data.favorites,item.id];const ok=persist({...store.data,favorites});renderCollection();saveButton($('bench-save'),selected);const restore=[...document.querySelectorAll('.card-save')].find(b=>b.dataset.saveId===item.id);if(restore)restore.focus({preventScroll:true});else if(state.section==='saved')document.querySelector('.card-open')?.focus({preventScroll:true});if(ok)toast(favorites.includes(item.id)?'已收藏在当前浏览器。':'已取消收藏。');}
function makeImage(art,title,thumb=true){const image=el('img');image.src=`assets/${art}${thumb?'-thumb':''}.webp`;image.alt=title;image.decoding='async';image.addEventListener('error',()=>{const p=image.parentElement;image.hidden=true;if(p&&!p.querySelector('.image-fallback'))p.append(el('span','image-fallback','预览暂时不可用，提示词仍可使用。'));});return image;}
function card(item){
 const article=el('article',`art-card ${item.type!=='prompt'?'skill-card':''} ${selected.id===item.id?'selected':''}`);article.setAttribute('role','listitem');article.dataset.itemId=item.id;
 const open=el('button','card-open');open.type='button';open.setAttribute('aria-label',`查看：${item.title}`);open.setAttribute('aria-pressed',String(selected.id===item.id));
 if(item.art){const media=el('div',`card-media ${item.ratio}`),img=makeImage(item.art,'');img.loading='lazy';media.append(img,el('span','card-type',item.media==='video'?'视频 · 运镜示意':'图片 · 原创示例'));if(item.media==='video'){const play=el('span','card-play');play.append(icon('play'));media.append(play);}open.append(media);}
 else{const visual=el('div','skill-visual');visual.append(icon(item.type==='skill'?'code':'sliders'),el('span','skill-tool',item.tool));open.append(visual);}
 const caption=el('div','card-caption');caption.append(el('h3','',item.title));if(!item.art)caption.append(el('p','skill-summary',item.summary));caption.append(el('p','',`${item.category} · ${typeLabels[item.type]}`));open.append(caption);open.addEventListener('click',()=>select(item,{focus:true}));
 const favorite=el('button','icon-button card-save');favorite.type='button';saveButton(favorite,item);favorite.addEventListener('click',()=>toggleFavorite(item));article.append(open,favorite);return article;
}
function baseItems(){return findItems(items,{...state,query:'',category:'all',media:'all',type:'all'},store.data);}
function renderFilters(){
 const base=baseItems();$('media-filters').replaceChildren();
 for(const [value,label,glyph]of[['all','全部',null],['image','图片','image'],['video','视频','video']]){const b=el('button');if(glyph)b.append(icon(glyph));b.append(document.createTextNode(label),el('span','filter-count',String(base.filter(x=>value==='all'||x.media===value).length)));b.setAttribute('aria-pressed',String(state.media===value));b.dataset.media=value;b.addEventListener('click',()=>{state.media=value;state.category='all';renderCollection();document.querySelector(`[data-media="${value}"]`)?.focus({preventScroll:true});});$('media-filters').append(b);}
 const categories=[...new Set(base.filter(x=>(state.media==='all'||x.media===state.media)&&(state.type==='all'||x.type===state.type)).map(x=>x.category))];if(state.category!=='all'&&!categories.includes(state.category))state.category='all';$('category-filters').replaceChildren();
 for(const value of['all',...categories]){const b=el('button','',value==='all'?'全部用途':value);b.setAttribute('aria-pressed',String(state.category===value));b.dataset.category=value;b.addEventListener('click',()=>{state.category=value;renderCollection();[...document.querySelectorAll('[data-category]')].find(n=>n.dataset.category===value)?.focus({preventScroll:true});});$('category-filters').append(b);}
}
function renderPlays(){
 $('plays-list').replaceChildren();for(const play of plays){const article=el('article','play-story'),img=makeImage(play.art,'');img.loading='lazy';const content=el('div','play-story-content');content.append(el('h2','',play.title),el('p','',play.summary));const list=el('ol');play.steps.forEach((step,index)=>{const li=el('li'),b=el('button'),label=el('span');label.append(el('span','step-number',String(index+1)),document.createTextNode(step.label));b.append(label,icon('arrow'));b.addEventListener('click',()=>select(items.find(x=>x.id===step.id),{focus:true}));li.append(b);list.append(li);});content.append(list);article.append(img,content);$('plays-list').append(article);}
}
function renderCollection(){
 const [title,description]=headings[state.section];$('page-title').textContent=title;$('page-description').textContent=description;document.querySelectorAll('[data-section]').forEach(b=>{if(b.dataset.section===state.section)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('saved-count').textContent=String(store.data.favorites.length);
 const isPlays=state.section==='plays';$('catalog-controls').hidden=isPlays;$('gallery').hidden=isPlays;$('plays-list').hidden=!isPlays;$('empty-state').hidden=true;$('collection-note').textContent=isPlays?'组合方法 · 等待实测':state.section==='skills'?'官方出处 · 未安装运行':'原创示例 · 提示词待实测';
 if(isPlays){$('result-count').textContent=`${plays.length} 个创作玩法`;renderPlays();return;}
 renderFilters();const visible=findItems(items,state,store.data);$('result-count').textContent=`${visible.length} 份${state.section==='skills'?'技能与工作流':'创作灵感'}`;$('gallery').replaceChildren(...visible.map(card));$('gallery').setAttribute('role','list');
 if(!visible.length){$('empty-state').hidden=false;const emptyCollection=['saved','history'].includes(state.section)&&!state.query&&state.media==='all'&&state.category==='all'&&state.type==='all';$('empty-title').textContent=emptyCollection?(state.section==='saved'?'把喜欢的灵感留下来':'从一个灵感开始'):'暂时没有找到';$('empty-description').textContent=emptyCollection?(state.section==='saved'?'点击条目上的收藏按钮，它会出现在这里。':'打开任意条目，就能在这里继续找回。'):'试试更短的关键词，或者清除筛选看看全部内容。';$('empty-action').textContent=emptyCollection?'去发现灵感':'清除筛选';$('empty-action').onclick=()=>{if(emptyCollection)setSection('discover');else resetFilters();};}
}
function resetFilters(){state.media='all';state.category='all';state.type='all';state.query='';$('search').value='';$('resource-type').value='all';renderCollection();}
function setSection(section){state.section=section;resetFilters();document.querySelector(`[data-section="${section}"]`)?.focus({preventScroll:true});}
function values(){if(!drafts.has(selected.id))drafts.set(selected.id,Object.fromEntries(selected.fields.map(f=>[f.key,f.value])));return drafts.get(selected.id);}
function updatePrompt(){$('prompt-output').value=compile(selected,values(),language);}
function select(item,options={}){if(!item)return;selected=item;persist({...store.data,history:[item.id,...store.data.history.filter(x=>x!==item.id)]});const hash=new URLSearchParams({item:item.id}).toString();if(location.hash!==`#${hash}`)history.pushState(null,'',`#${hash}`);renderCollection();renderBench();if(options.focus){$('workbench').focus({preventScroll:true});if(window.innerWidth<=900)$('workbench').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}}
function setPlaying(b){motionPlaying=!motionPlaying;$('bench-preview').querySelector('.motion-stage')?.classList.toggle('playing',motionPlaying);decorate(b,motionPlaying?'pause':'play');b.setAttribute('aria-label',motionPlaying?'暂停运镜示意':'播放运镜示意');b.setAttribute('aria-pressed',String(motionPlaying));}
function showLarge(){$('preview-image').src=`assets/${selected.art}.webp`;$('preview-image').alt=selected.title;$('preview-caption').textContent=`${selected.title} · 原创AI视觉示例`;$('preview-dialog').showModal();}
function renderBench(){
 motionPlaying=false;$('bench-content').scrollTop=0;$('selected-title').textContent=selected.title;$('selected-description').textContent=selected.summary;$('bench-badges').replaceChildren(el('span','',typeLabels[selected.type]),el('span','',selected.status));saveButton($('bench-save'),selected);$('bench-preview').replaceChildren();
 if(selected.art){if(selected.media==='video'){const stage=el('div',`motion-stage ${selected.movement}`);stage.append(makeImage(selected.art,selected.title),el('span','preview-label','二维运镜示意'));const controls=el('div','motion-controls'),b=el('button','icon-button');b.type='button';decorate(b,'play');b.setAttribute('aria-label','播放运镜示意');b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>setPlaying(b));controls.append(b,el('span','','12秒循环示意'));stage.append(controls);$('bench-preview').append(stage);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)$('bench-preview').append(el('p','fine-print','已减少动态效果，示意保持静止。'));}
 else{const b=el('button','preview-button');b.setAttribute('aria-label',`放大预览：${selected.title}`);b.append(makeImage(selected.art,selected.title),el('span','preview-label','原创AI视觉示例 · 点开看大图'));b.addEventListener('click',showLarge);$('bench-preview').append(b);}}
 else{const visual=el('div','bench-skill'),text=el('div');text.append(el('strong','',selected.tool),el('span','',selected.type==='skill'?'官方 Agent Skill':'官方模板使用指引'));visual.append(icon(selected.type==='skill'?'code':'sliders'),text);$('bench-preview').append(visual);}
 const current=values();$('material-fields').replaceChildren();for(const f of selected.fields){const label=el('label','material-field',f.label),input=el('input');input.id=`material-${f.key}`;input.name=f.key;input.value=current[f.key];input.maxLength=300;input.autocomplete='off';input.addEventListener('input',()=>{current[f.key]=input.value;updatePrompt();});label.append(input);$('material-fields').append(label);}updatePrompt();decorate($('copy-prompt'),'copy',selected.type==='prompt'?'复制完整提示词':'复制使用提示词');$('usage-steps').replaceChildren(...selected.steps.map(s=>el('li','',s)));$('usage-requirements').textContent=selected.requirements;$('usage-tip').textContent=selected.tip;$('skill-command').replaceChildren();
 if(selected.command){const code=el('code','command',selected.command),b=el('button','text-button command-button','复制官方安装命令');b.type='button';b.addEventListener('click',()=>copyText(selected.command,'命令已复制，请在自己的环境检查后运行。'));$('skill-command').append(code,b);}
 $('source-link').href=selected.source.url;decorate($('source-link'),'external',selected.source.label);$('workbench').querySelector('.instructions').open=false;document.querySelector('.inline-confirm')?.remove();document.querySelector('.manual-copy')?.remove();
}
async function copyText(text,success){try{if(!navigator.clipboard?.writeText)throw Error('clipboard');await navigator.clipboard.writeText(text);document.querySelector('.manual-copy')?.remove();toast(success);return true;}catch{document.querySelector('.manual-copy')?.remove();const box=el('div','manual-copy'),label=el('label','','手动复制文本'),area=el('textarea');area.value=text;area.readOnly=true;area.rows=4;label.append(area);box.append(label);$('bench-content').append(box);area.focus();area.select();toast('自动复制不可用。已选中文本，请按 Ctrl+C 或长按复制。');return false;}}
function resetMaterials(){if(selected.fields.every(f=>values()[f.key]===f.value)||document.querySelector('.inline-confirm'))return;const box=el('div','inline-confirm'),cancel=el('button','secondary-button','保留我的内容'),confirm=el('button','secondary-button','恢复示例');cancel.type=confirm.type='button';cancel.addEventListener('click',()=>{box.remove();$('reset-materials').focus();});confirm.addEventListener('click',()=>{drafts.delete(selected.id);renderBench();$('reset-materials').focus();toast('已恢复当前条目的示例材料。');});box.append(el('p','','恢复示例会覆盖当前条目的材料。'),cancel,confirm);$('material-form').append(box);cancel.focus();}
 for(const[id,glyph,label]of[['search-icon','search'],['empty-icon','search'],['more-filters','sliders','更多筛选'],['history-button','history','最近浏览'],['download-prompt','download'],['share-item','external'],['close-preview','close'],['close-about','close'],['return-to-library','arrow']])decorate($(id),glyph,label);
$('theme-toggle').addEventListener('click',()=>{persist({...store.data,theme:store.data.theme==='dark'?'light':'dark'});applyTheme();});document.querySelectorAll('[data-section]').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));$('history-button').addEventListener('click',()=>setSection('history'));
$('search').addEventListener('input',()=>{state.query=$('search').value;renderCollection();});$('sort').addEventListener('change',()=>{state.sort=$('sort').value;renderCollection();});$('resource-type').addEventListener('change',()=>{state.type=$('resource-type').value;state.category='all';if(state.section==='discover'&&['skill','workflow'].includes(state.type))state.section='skills';else if(state.section==='skills'&&state.type==='prompt')state.section='discover';renderCollection();});$('more-filters').addEventListener('click',()=>{const open=$('advanced-filters').hidden;$('advanced-filters').hidden=!open;$('more-filters').setAttribute('aria-expanded',String(open));});
$('return-to-library').addEventListener('click',()=>{$('collection').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});(state.section==='plays'?$('history-button'):$('search')).focus({preventScroll:true});});
$('bench-save').addEventListener('click',()=>toggleFavorite(selected));$('material-form').addEventListener('submit',event=>event.preventDefault());$('reset-materials').addEventListener('click',resetMaterials);
for(const lang of['zh','en'])$('language-'+lang).addEventListener('click',()=>{language=lang;$('language-zh').setAttribute('aria-pressed',String(lang==='zh'));$('language-en').setAttribute('aria-pressed',String(lang==='en'));updatePrompt();});
$('copy-prompt').addEventListener('click',async()=>{const b=$('copy-prompt');b.disabled=true;await copyText($('prompt-output').value,'提示词已复制，可以粘贴到目标工具。');b.disabled=false;});
$('download-prompt').addEventListener('click',()=>{const blob=new Blob([exportText(selected,$('prompt-output').value)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=el('a');link.href=url;link.download=`魔法工坊-${selected.id}.txt`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已请求下载TXT，请在浏览器下载记录中查看。');});
$('share-item').addEventListener('click',()=>{const url=new URL(location.href);url.search='';url.hash=new URLSearchParams({item:selected.id}).toString();copyText(url.toString(),'条目链接已复制，不含你的替换材料。');});
$('about-button').addEventListener('click',()=>{$('storage-status').textContent=store.available?'本地收藏和浏览记录可用；清除浏览器数据会删除这些记录。':'浏览器存储不可用，收藏与浏览记录仅本页有效。';$('about-dialog').showModal();});$('clear-history').addEventListener('click',()=>{persist({...store.data,history:[]});renderCollection();toast('已清除最近浏览，收藏保留。');});
for(const name of['preview','about']){const dialog=$(name+'-dialog');$('close-'+name).addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});}
function fromLocation(){selected=itemFromHash(location.hash,items)||items[0];renderCollection();renderBench();}window.addEventListener('hashchange',fromLocation);window.addEventListener('popstate',fromLocation);window.addEventListener('storage',event=>{if(event.key===STORE_KEY){store.refresh(event.newValue);applyTheme();renderCollection();saveButton($('bench-save'),selected);}});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)&&!event.target.isContentEditable&&!document.querySelector('dialog[open]')){event.preventDefault();if(state.section==='plays')setSection('discover');$('search').focus();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&motionPlaying){motionPlaying=false;$('bench-preview').querySelector('.motion-stage')?.classList.remove('playing');const b=$('bench-preview').querySelector('.motion-controls button');if(b){decorate(b,'play');b.setAttribute('aria-label','播放运镜示意');b.setAttribute('aria-pressed','false');}}});
if(selected.type!=='prompt')state.section='skills';applyTheme();renderCollection();renderBench();
